### ISSUE TITLE
Thank you for releasing this!

### ISSUE THREAD

**Issue by Dreaming381** [grapefrukt/usfxr#2]
No issues. I just wanted to thank you for releasing this in UPM format and making it useful. I couldn't find a forum or anywhere else to post this, so I am doing so here.

I actually got this working in an open-source DOTS project with a custom audio sampling and spatialization engine. I wanted customizable sounds generated in the editor rather than binary assets and this was the perfect fit! I'm currently using it for every sound in the project, and the quality, depth, and dynamism I managed to squeeze out of this is far greater than I anticipated!

Anyways, you can close this issue whenever. I just wanted to thank you for bringing new life to this tool!

**Comment by grapefrukt** [comment]
Sorry, it seems I completely missed this when you posted it. Glad it was of use to you!
